#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The screen's Japanese names for the built-in patches (Suiko-style: the name, and the instrument's kanji
beneath it) -> firmware/src/app/fumi_kanji.h: a 16 px font holding just the kanji those names use, one
glyph slot per character from '!' up, and each name as a string of those slots. The glyphs are rendered
from Noto Sans CJK JP Bold (SIL Open Font License 1.1, Google / Adobe); any copy of it will do:

  tools/gen_kanji.py firmware/src/app/fumi_kanji.h [NotoSansCJKjp-Bold.otf]

The header is checked in, so building does not need the font; tests/run_tests.sh regenerates and compares
it when a copy is found (FUMI_CJK_FONT, or the usual places). The UTF-8 names are in fumi_patches.h."""
import os
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fumi_patches import PATCHES  # noqa: E402

PX, PAD, FIRST = 16, 2, 0x21
CANDIDATES = ["/Applications/Ableton Live 12 Standard.app/Contents/App-Resources/Fonts/NotoSansCJKjp-Bold.otf",
              "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc", "/usr/share/fonts/noto-cjk/NotoSansCJK-Bold.ttc"]


def find_font(arg):
    for c in [arg, os.environ.get("FUMI_CJK_FONT"), *CANDIDATES]:
        if c and Path(c).exists():
            return c
    return None


def main(out, font_arg=None):
    path = find_font(font_arg)
    if not path:
        raise SystemExit("gen_kanji: no Noto Sans CJK font found (pass its path, or set FUMI_CJK_FONT)")
    chars = []
    for _, ja, _ in PATCHES:
        for ch in ja:
            if ch not in chars:
                chars.append(ch)
    assert len(chars) <= 0x7E - FIRST + 1
    font = ImageFont.truetype(path, PX)
    asc, desc = font.getmetrics()
    top = min(font.getbbox(ch)[1] for ch in chars)
    bottom = max(font.getbbox(ch)[3] for ch in chars)
    h = bottom - top
    data, offs, advs, bws = [], [], [], []
    for ch in chars:
        adv = int(round(font.getlength(ch)))
        bw = adv + 2 * PAD
        img = Image.new("L", (bw, asc + desc), 0)
        ImageDraw.Draw(img).text((PAD, 0), ch, font=font, fill=255)
        img = img.crop((0, top, bw, top + h))
        px = [min(15, (v + 8) // 17) for v in img.tobytes()]
        offs.append(len(data))
        for y in range(h):
            row = px[y * bw:(y + 1) * bw] + [0]
            for x in range(0, bw, 2):
                data.append((row[x] << 4) | row[x + 1])
        advs.append(adv)
        bws.append(bw)
    L = ["/* generated by tools/gen_kanji.py: the kanji of the built-in patches' Japanese names, from Noto Sans",
         " * CJK JP Bold (SIL OFL 1.1). Slot '!' + i holds the character CHARS[i]; FM_PATCH_JA_LCD are the names",
         " * as slot strings for cv_text(&FONT_JP, ...). Do not edit: tools/gen_kanji.py */",
         "#pragma once", "#include <stdint.h>",
         "/* " + " ".join(f"{chr(FIRST + i)}={ch}" for i, ch in enumerate(chars)) + " */",
         f"static const uint8_t FONT_JP_DATA[{len(data)}] = {{"]
    for i in range(0, len(data), 24):
        L.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
    L += ["};",
          f"static const uint16_t FONT_JP_OFF[{len(offs)}] = {{" + ", ".join(map(str, offs)) + "};",
          f"static const uint8_t FONT_JP_ADV[{len(advs)}] = {{" + ", ".join(map(str, advs)) + "};",
          f"static const uint8_t FONT_JP_BW[{len(bws)}] = {{" + ", ".join(map(str, bws)) + "};",
          f"static const felucca_font_t FONT_JP = {{ {h}, {PAD}, {FIRST}, {FIRST + len(chars) - 1}, FONT_JP_ADV, FONT_JP_BW, FONT_JP_OFF, FONT_JP_DATA }};",
          f"static const char *const FM_PATCH_JA_LCD[{len(PATCHES)}] = {{" +
          ", ".join('"' + "".join(chr(FIRST + chars.index(ch)).replace("\\", "\\\\").replace('"', '\\"') for ch in ja) + '"' for _, ja, _ in PATCHES) + "};", ""]
    Path(out).write_text("\n".join(L))
    print(f"kanji: {out} ({len(chars)} glyphs, {h} px, {len(data)} B) from {Path(path).name}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
